---
- name: Install and Configure Nginx on AWS and Azure
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Verify that Nginx is running
      shell: systemctl is-active nginx
      register: nginx_status
      changed_when: false
      failed_when: nginx_status.stdout != "active"

    - name: Show Nginx status
      debug:
        msg: "Nginx is {{ nginx_status.stdout }}"
